<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Expense_Tracker.Domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dodo.Primitives" Version="5.0.0" />
    <PackageReference Include="Dodo.Primitives.Generation" Version="5.0.0" />
    <PackageReference Include="ErrorOr" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
  </ItemGroup>

</Project>
